test: print config.yaml during test-examples workflow

diff --git a/.github/workflows/test-examples.yaml b/.github/workflows/test-examples.yaml
--- a/.github/workflows/test-examples.yaml
+++ b/.github/workflows/test-examples.yaml
@@ -71,5 +71,8 @@ jobs:
     - name: Authenticate unikraft CLI
       run: echo $UKC_TOKEN | unikraft login --token -
 
+    - name: Debug – print CLI config
+      run: cat ~/.config/unikraft/config.yaml || echo "Config file not found"
+
     - name: Run tests
       run: pytest --log-cli-level=INFO
